name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: go_to
      #run: cd the_next_week/build
    #- name: configure
      #run: ./configure
    - name: make
      run: cd the_next_week/build/ && make
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
    - name: SonarCloud Scan
    # You may pin to the exact commit or the version.
    # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        projectBaseDir: the_next_week/src
